body:
  - type: textarea
    attributes:
      label: Goal
      description: "What are you trying to achieve? Provide explanatory images if possible/needed."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Source Yaml
      description: "Provide the source YAML code where you started."
      render: yaml
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Which step did you already try?
      description: "Show YAML code for the attempt(s) that you already made."
      render: yaml
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "Describe the problem that you encounter."
    validations:
      required: false

  - type: checkboxes
    id: Documentation
    attributes:
      label: Read the documentation
      description: "Reading the documentation before asking a question saves time by providing immediate answers to common issues, helping you understand the basics and resolve problems independently. It also allows you to ask more informed, specific questions, increasing the likelihood of getting effective help."
      options:
        - label: I have read the documentation
    validations:
      required: true

  - type: markdown
    attributes:
      value: "<sup>[Documentation](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#table-of-contents) / [Examples](https://github.com/Clooos/Bubble-Card/discussions/categories/share-your-custom-styles-templates-and-dashboards)</sup>"
 
  - type: markdown
    attributes:
      value: |
        ---
        
        Thanks for completing our form and asking your question!
